name: Neekasho CI pipeline
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 1
  push: null
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      passed: '${{ steps.fetchResult.outputs.PASSED }}'
      failed: '${{ steps.fetchResult.outputs.FAILED }}'
      skipped: '${{ steps.fetchResult.outputs.SKIPPED }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test --reporter=json > test-results.json
        env:
          EMAIL: '${{ secrets.EMAIL }}'
          PASSWORD: '${{ secrets.PASSWORD }}'
          USERNAME: '${{ secrets.USERNAME }}'
      - name: Fetch test results
        id: fetchResult
        run: |
          STATS=$(cat test-results.json | jq '.stats')
          PASSED=$(jq '.stats.expected' test-results.json)
          FAILED=$(jq '.stats.unexpected' test-results.json)
          SKIPPED=$(jq '.stats.skipped' test-results.json)

          echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
          echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
          echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results.json
          path: test-results.json
  notification:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Send notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: '${{ secrets.SEND_MAIL_FROM_USERNAME }}'
          password: '${{ secrets.SEND_MAIL_FROM_PASSWORD }}'
          subject: 'Nekasho - Execution Details'
          to: '${{ secrets.SEND_MAIL_TO }}'
          from: '${{ secrets.SEND_MAIL_FROM_USERNAME }}'
          body: |
            Nekasho - Test Execution Details

            Test Execution Summary:
            ✅ Passed: ${{ needs.test.outputs.passed }}
            ❌ Failed: ${{ needs.test.outputs.failed }}
            ⚠️ Skipped: ${{ needs.test.outputs.skipped }}

            Regards,
            Nekasho CI
