name: Neekasho CI pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  push:

env: 
  GITHUB_WORKSPACE: tests/specs

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      passed: ${{ steps.fetchResult.outputs.PASSED }}
      failed: ${{ steps.fetchResult.outputs.FAILED }}
      skipped: ${{ steps.fetchResult.outputs.SKIPPED }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test login.spec.ts --reporter=json > test-results.json
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Fetch test results
        id: fetchResult
        run: |
          STATS=$(cat test-results.json | jq '.stats')
          PASSED=$(jq '.stats.expected' test-results.json)
          FAILED=$(jq '.stats.unexpected' test-results.json)
          SKIPPED=$(jq '.stats.skipped' test-results.json)

          echo "PASSED=$PASSED" >> $GITHUB_OUTPUT
          echo "FAILED=$FAILED" >> $GITHUB_OUTPUT
          echo "SKIPPED=$SKIPPED" >> $GITHUB_OUTPUT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: index.html
          path: playwright-report